[package]
name = "pg-libs"
version = "0.1.0"
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
description = "A toolkit for constructing, transforming, and synthesizing Pauli graphs"
readme = "README.md"
documentation = "https://docs.rs/pg-libs"
keywords = ["Quantum", "Quantinuum"]
categories = ["compilers", "science::quantum-computing"]

[features]
default = []
simd = ["pg-bitpacked/simd", "pg-qm-tableau/simd", "pg-greedy-synth/simd"]

[dependencies]
pg-core = { path = "../pg-core" }
pg-canonical-form = { path = "../pg-passes/pg-canonical-form" }
pg-optimise = { path = "../pg-passes/pg-optimise" }
pg-greedy-synth = { path = "../pg-passes/pg-greedy-synth" }
pg-rebase = { path = "../pg-passes/pg-rebase" }
pg-tk = { path = "../pg-converters/pg-tk" }
pg-qm-tableau = { path = "../pg-qm-tableau" }
pg-bitpacked = { path = "../pg-kernels/pg-bitpacked" }
pg-ir-kernels = { path = "../pg-kernels/pg-ir-kernels" }
pg-utils = { path = "../pg-utils/pg-utils" }

[lints]
workspace = true
