name: Get the hugrenv version used in this branch
description: Reads hugrenv.lock to extract the version field

inputs:
  install-path:
    description: "The path to the hugrenv installation (default: /tmp/hugrverse)"
    required: false
    default: "/tmp/hugrverse"
  target:
    description: "The target platform (e.g. manylinux_2_28_x86_64, macos_15_0_aarch64, win_amd64)"
    required: false
    default: "manylinux_2_28_x86_64"
  packages:
    description: "Comma-separated list of packages to install (default: llvm,tket)"
    required: false
    default: "llvm,tket"

runs:
  using: composite
  steps:
    - name: Get version from hugrenv.lock
      shell: bash
      id: version
      run: |
        version=$(jq -r '.version' hugrenv.lock)
        echo "HUGRENV_VERSION=$version" >> $GITHUB_ENV
    - name: Download from hugrverse-env
      shell: bash
      run: |
        install_path="${{ inputs.install-path }}"
        target="${{ inputs.target }}"
        packages="${{ inputs.packages }}"
        mkdir -p $install_path
        echo "Downloading hugrenv version $HUGRENV_VERSION for target $target to $install_path"
        for package in ${packages//,/ }; do
          echo "Downloading package $package"
          url="https://github.com/Quantinuum/hugrverse-env/releases/download/v${HUGRENV_VERSION}/hugrenv-${package}-${target}.tar.gz"
          curl -L "$url" | tar -xzf - -C $install_path --strip-components=1
        done
    - name: Set environment variables
      shell: bash
      run: |
        echo "Setting environment variables for hugrenv"
        echo "HUGRENV_PATH=${{ inputs.install-path }}" >> $GITHUB_ENV
        # if tket is in the packages, set TKET_C_API_PATH
        if [[ "${{ inputs.packages }}" == *"tket"* ]]; then
          echo "Setting TKET_C_API_PATH to ${{ inputs.install-path }}"
          echo "TKET_C_API_PATH=${{ inputs.install-path }}" >> $GITHUB_ENV
        fi;
        # if llvm is in the packages, set LLVM_SYS_211_PREFIX and LIBCLANG_PATH
        if [[ "${{ inputs.packages }}" == *"llvm"* ]]; then
          echo "Setting LLVM_SYS_211_PREFIX to ${{ inputs.install-path }}"
          echo "LLVM_SYS_211_PREFIX=${{ inputs.install-path }}" >> $GITHUB_ENV
          echo "Setting LIBCLANG_PATH to ${{ inputs.install-path }}/lib"
          echo "LIBCLANG_PATH=${{ inputs.install-path }}/lib" >> $GITHUB_ENV
        fi;
        # if linux, set LD_LIBRARY_PATH to include lib and lib64
        if [[ "${{ inputs.target }}" == *linux* ]]; then
          echo "Setting LD_LIBRARY_PATH to include ${{ inputs.install-path }}/lib and ${{ inputs.install-path }}/lib64"
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${{ inputs.install-path }}/lib:${{ inputs.install-path }}/lib64:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
        fi;
        # if macos, set DYLD_LIBRARY_PATH to include lib
        if [[ "${{ inputs.target }}" == *macos* ]]; then
          echo "Setting DYLD_LIBRARY_PATH to include ${{ inputs.install-path }}/lib"
          echo "DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:${{ inputs.install-path }}/lib:${DYLD_LIBRARY_PATH}" >> $GITHUB_ENV
        fi;
        # if windows, set PATH to include bin
        if [[ "${{ inputs.target }}" == *win* ]]; then
          echo "Setting PATH to include ${{ inputs.install-path }}/lib and ${{ inputs.install-path }}/lib64"
          echo "${{ inputs.install-path }}/lib" >> $GITHUB_PATH
          echo "${{ inputs.install-path }}/lib64" >> $GITHUB_PATH
        fi;
        echo "Setting PATH to include ${{ inputs.install-path }}/bin"
        echo "${{ inputs.install-path }}/bin:$PATH" >> $GITHUB_PATH



