# Filters used by [dorny/path-filters](https://github.com/dorny/paths-filter)
# to detect changes in each subproject, and only run the corresponding jobs.

rust-core: &rust-core
  - "tket/tket-rs/**"
  - "Cargo.toml"
  - "Cargo.lock"
  - "hugrenv.lock"

rust:
  - *rust-core
  - "tket/tket-qsystem/**"
  - "tket/badger-optimiser/**"
  - "tket/compile-rewriter/**"
  - "tket/tket1-passes/**"
  - "tket/qis-compiler/rust/**"
  - "tket/qis-compiler/Cargo.toml"

pg-libs:
  - "pg-libs/**"

python:
  - *rust-core
  - "test_files/**"
  - "tket/tket-py/**"
  - "tket/tket-eccs/**"
  - "tket/tket-exts/**"
  - "pyproject.toml"
  - "uv.lock"

qis:
  - *rust-core
  - "tket/qis-compiler/**"
  - "pyproject.toml"
  - "uv.lock"

extensions:
  - "tket/tket-exts/src/tket_exts/data/tket/**"
