# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    commit-message:
      # Use a conventional commit tag
      prefix: "chore(deps-rs)"
    labels:
      - "A-rust"
      - "X-dependabot"
    groups:
      hugr:
        patterns: ["hugr*"]
      dev:
        dependency-type: "development"
        update-types: ["patch", "minor"]
      patch:
        update-types: ["patch"]
      minor:
        update-types: ["minor"]
      # Major updates still generate individual PRs

  - package-ecosystem: "uv"
    directories: # Location of package manifests
      - "/"
      - "/tket-py"
      - "/tket-eccs"
      - "/tket-exts"
    schedule:
      interval: "weekly"
    commit-message:
      # Use a conventional commit tag
      prefix: "chore(deps-py)"
    labels:
      - "A-python"
      - "X-dependabot"
    groups:
      hugr:
        patterns: ["hugr*"]
      dev:
        dependency-type: "development"
        update-types: ["patch", "minor"]
      patch:
        update-types: ["patch"]
      minor:
        update-types: ["minor"]
      # Major updates still generate individual PRs

    # Do not bump the minimal version of dependencies.
    #
    # Bumping the minimum can be a breaking change for downstream python users,
    # as they may break their dependency resolution and prevent them from updating.
    #
    # Ideally we'd widen the upper bound.
    # The dependabot documentation indicates this can be done by setting versioning-strategy to "widen",
    # but this returned errors saying that the value is invalid.
    # (https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference#versioning-strategy--)
    #
    # See the uv versioning-strategy issue:
    # <https://github.com/dependabot/dependabot-core/issues/15290>
    versioning-strategy: "lockfile-only"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      # Use a conventional commit tag
      prefix: "ci(deps)"
    labels:
      - "A-ci"
      - "X-dependabot"
