[package]
name = "tk-pg-libs"
version = "0.1.0"
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
description = "A toolkit for constructing, transforming, and synthesizing Pauli graphs"
readme = "README.md"
documentation = "https://docs.rs/tk-pg-libs"
keywords = ["Quantum", "Quantinuum"]
categories = ["compilers", "science::quantum-computing"]

[features]
default = []
unstable_simd = ["tk-pg-bitpacked/unstable_simd", "tk-pg-qm-tableau/unstable_simd", "tk-pg-greedy-synth/unstable_simd"]

[dependencies]
tk-pg-core = { path = "../tk-pg-core" }
tk-pg-canonical-form = { path = "../pg-passes/tk-pg-canonical-form" }
tk-pg-optimize = { path = "../pg-passes/tk-pg-optimize" }
tk-pg-greedy-synth = { path = "../pg-passes/tk-pg-greedy-synth" }
tk-pg-rebase = { path = "../pg-passes/tk-pg-rebase" }
tk-pg-converter = { path = "../pg-converters/tk-pg-converter" }
tk-pg-qm-tableau = { path = "../tk-pg-qm-tableau" }
tk-pg-bitpacked = { path = "../pg-kernels/tk-pg-bitpacked" }
tk-pg-ir-kernels = { path = "../pg-kernels/tk-pg-ir-kernels" }
tk-pg-utils = { path = "../pg-utils/tk-pg-utils" }

[lints]
workspace = true
