# List the available commands
help:
    @just --list --justfile {{justfile()}}

# Re-generate all hugr files and their mermaid diagrams.
r: run-hugrs

# Re-generate all hugr files.
run-hugrs:
    uv run --no-project "test_hugrs.py"
    


# Re-generate a single hugr file.
rh example:
    uv run --no-project "test_hugrs.py" "{{example}}"
