---
config:
    layout: elk
---
graph LR
    subgraph 0 ["(0) Module"]
        direction LR
        subgraph 1 ["(1) [**FuncDefn: #quot;__main__.main#quot;**]"]
            direction LR
            style 1 stroke:#832561,stroke-width:3px
            2["(2) Input"]
            3["(3) Output"]
            subgraph 4 ["(4) CFG"]
                direction LR
                subgraph 5 ["(5) DataflowBlock"]
                    direction LR
                    6["(6) Input"]
                    7["(7) Output"]
                    8["(8) tket.quantum.QAlloc"]
                    9["(9) tket.quantum.QAlloc"]
                    11["(11) tket.modifier.DaggerModifier"]
                    266["(266) LoadFunction"]
                    12["(12) CallIndirect"]
                    13["(13) collections.borrow_arr.new_array"]
                    14["(14) collections.borrow_arr.to_array"]
                    15["(15) tket.debug.StateResult"]
                    16["(16) collections.borrow_arr.from_array"]
                    17["(17) collections.borrow_arr.unpack"]
                    18["(18) prelude.MakeTuple"]
                    19["(19) tket.quantum.QFree"]
                    20["(20) prelude.MakeTuple"]
                    21["(21) tket.quantum.QFree"]
                    22["(22) prelude.MakeTuple"]
                    23["(23) Tag"]
                    6-."0:0".->8
                    8--"0:1<br>qubit"-->12
                    8-."1:0".->9
                    9--"0:2<br>qubit"-->12
                    9-."1:3".->12
                    266--"0:0<br>[qubit, qubit] -> [qubit, qubit]"-->12
                    12--"0:0<br>qubit"-->13
                    12--"1:1<br>qubit"-->13
                    12-."2:1".->15
                    13--"0:0<br>borrow_array(2, qubit)"-->14
                    14--"0:0<br>array(2, qubit)"-->15
                    15--"0:0<br>array(2, qubit)"-->16
                    15-."1:1".->19
                    16--"0:0<br>borrow_array(2, qubit)"-->17
                    17--"0:0<br>qubit"-->21
                    17--"1:0<br>qubit"-->19
                    19-."0:1".->21
                    21-."0:1".->7
                    23--"0:0<br>Unit"-->7
                end
                24["(24) ExitBlock"]
                5-."0:0".->24
            end
            2-."0:0".->4
            4-."0:0".->3
        end
        subgraph 25 ["(25) FuncDefn: #quot;__main__.main.__WithBlock__0#quot;"]
            direction LR
            26["(26) Input"]
            27["(27) Output"]
            subgraph 28 ["(28) CFG"]
                direction LR
                subgraph 29 ["(29) DataflowBlock"]
                    direction LR
                    30["(30) Input"]
                    31["(31) Output"]
                    32["(32) LoadFunction"]
                    33["(33) tket.modifier.ControlModifier"]
                    34["(34) collections.borrow_arr.new_array"]
                    35["(35) collections.borrow_arr.to_array"]
                    36["(36) CallIndirect"]
                    37["(37) collections.borrow_arr.from_array"]
                    38["(38) collections.borrow_arr.unpack"]
                    39["(39) Call"]
                    40["(40) prelude.MakeTuple"]
                    41["(41) Tag"]
                    30--"0:0<br>qubit"-->34
                    30--"1:2<br>qubit"-->36
                    30-."2:3".->36
                    32--"0:0<br>[qubit] -> [qubit]"-->33
                    33--"0:0<br>[array(1, qubit), qubit] -> [array(1, qubit), qubit]"-->36
                    34--"0:0<br>borrow_array(1, qubit)"-->35
                    35--"0:1<br>array(1, qubit)"-->36
                    36--"0:0<br>array(1, qubit)"-->37
                    36--"1:2<br>qubit"-->31
                    36-."2:2".->39
                    37--"0:0<br>borrow_array(1, qubit)"-->38
                    38--"0:0<br>qubit"-->39
                    39--"0:1<br>qubit"-->31
                    39-."1:3".->31
                    41--"0:0<br>Unit"-->31
                end
                42["(42) ExitBlock"]
                29-."0:0".->42
            end
            26--"0:0<br>qubit"-->28
            26--"1:1<br>qubit"-->28
            26-."2:2".->28
            28--"0:0<br>qubit"-->27
            28--"1:1<br>qubit"-->27
            28-."2:2".->27
        end
        subgraph 43 ["(43) FuncDefn: #quot;__main__.main.__WithBlock__1#quot;"]
            direction LR
            44["(44) Input"]
            45["(45) Output"]
            subgraph 46 ["(46) CFG"]
                direction LR
                subgraph 47 ["(47) DataflowBlock"]
                    direction LR
                    48["(48) Input"]
                    49["(49) Output"]
                    50["(50) Call"]
                    51["(51) Call"]
                    52["(52) prelude.MakeTuple"]
                    53["(53) Call"]
                    54["(54) prelude.MakeTuple"]
                    55["(55) Tag"]
                    48--"0:0<br>qubit"-->51
                    48-."1:1".->50
                    50--"0:1<br>float64"-->53
                    50-."1:2".->51
                    51--"0:0<br>qubit"-->53
                    51-."1:3".->53
                    53--"0:1<br>qubit"-->49
                    53-."1:2".->49
                    55--"0:0<br>Unit"-->49
                end
                56["(56) ExitBlock"]
                47-."0:0".->56
            end
            44--"0:0<br>qubit"-->46
            44-."1:1".->46
            46--"0:0<br>qubit"-->45
            46-."1:1".->45
        end
        subgraph 57 ["(57) FuncDefn: #quot;__main__.get_f#quot;"]
            direction LR
            58["(58) Input"]
            59["(59) Output"]
            subgraph 60 ["(60) CFG"]
                direction LR
                subgraph 61 ["(61) DataflowBlock"]
                    direction LR
                    62["(62) Input"]
                    63["(63) Output"]
                    64["(64) LoadConstant"]
                    65["(65) const:custom:u64(1)"]
                    66["(66) LoadConstant"]
                    67["(67) const:custom:u64(3)"]
                    68["(68) Call"]
                    69["(69) Tag"]
                    62-."0:3".->68
                    64--"0:0<br>int(6)"-->68
                    65--"0:0<br>int(6)"-->64
                    66--"0:1<br>int(6)"-->68
                    67--"0:0<br>int(6)"-->66
                    68--"0:1<br>float64"-->63
                    68-."1:2".->63
                    69--"0:0<br>Unit"-->63
                end
                70["(70) ExitBlock"]
                61-."0:0".->70
            end
            58-."0:0".->60
            60--"0:0<br>float64"-->59
            60-."1:1".->59
        end
        subgraph 71 ["(71) FuncDefn: #quot;__main__.foo2#quot;"]
            direction LR
            72["(72) Input"]
            73["(73) Output"]
            subgraph 74 ["(74) CFG"]
                direction LR
                subgraph 75 ["(75) DataflowBlock"]
                    direction LR
                    76["(76) Input"]
                    77["(77) Output"]
                    78["(78) tket.quantum.S"]
                    79["(79) prelude.MakeTuple"]
                    80["(80) LoadConstant"]
                    81["(81) const:custom:u64(1)"]
                    82["(82) LoadConstant"]
                    83["(83) const:custom:u64(6)"]
                    84["(84) Call"]
                    85["(85) prelude.MakeTuple"]
                    86["(86) prelude.UnpackTuple"]
                    87["(87) tket.rotation.from_halfturns_unchecked"]
                    88["(88) tket.quantum.Rx"]
                    89["(89) prelude.MakeTuple"]
                    90["(90) Tag"]
                    76--"0:0<br>qubit"-->78
                    76-."1:3".->84
                    78--"0:0<br>qubit"-->88
                    80--"0:0<br>int(6)"-->84
                    81--"0:0<br>int(6)"-->80
                    82--"0:1<br>int(6)"-->84
                    83--"0:0<br>int(6)"-->82
                    84--"0:0<br>float64"-->85
                    84-."1:2".->77
                    85--"0:0<br>[float64]"-->86
                    86--"0:0<br>float64"-->87
                    87--"0:1<br>rotation"-->88
                    88--"0:1<br>qubit"-->77
                    90--"0:0<br>Unit"-->77
                end
                91["(91) ExitBlock"]
                75-."0:0".->91
            end
            72--"0:0<br>qubit"-->74
            72-."1:1".->74
            74--"0:0<br>qubit"-->73
            74-."1:1".->73
        end
        subgraph 92 ["(92) FuncDefn: #quot;__main__.foo3#quot;"]
            direction LR
            93["(93) Input"]
            94["(94) Output"]
            subgraph 95 ["(95) CFG"]
                direction LR
                subgraph 96 ["(96) DataflowBlock"]
                    direction LR
                    97["(97) Input"]
                    98["(98) Output"]
                    99["(99) LoadConstant"]
                    100["(100) const:custom:u64(2)"]
                    101["(101) arithmetic.conversions.convert_s"]
                    102["(102) arithmetic.float.fdiv"]
                    103["(103) prelude.MakeTuple"]
                    104["(104) prelude.UnpackTuple"]
                    105["(105) tket.rotation.from_halfturns_unchecked"]
                    106["(106) tket.quantum.Rx"]
                    107["(107) prelude.MakeTuple"]
                    108["(108) Tag"]
                    97--"0:0<br>qubit"-->106
                    97--"1:0<br>float64"-->102
                    99--"0:0<br>int(6)"-->101
                    100--"0:0<br>int(6)"-->99
                    101--"0:1<br>float64"-->102
                    102--"0:0<br>float64"-->103
                    103--"0:0<br>[float64]"-->104
                    104--"0:0<br>float64"-->105
                    105--"0:1<br>rotation"-->106
                    106--"0:1<br>qubit"-->98
                    108--"0:0<br>Unit"-->98
                end
                109["(109) ExitBlock"]
                96-."0:0".->109
            end
            93--"0:0<br>qubit"-->95
            93--"1:1<br>float64"-->95
            95--"0:0<br>qubit"-->94
        end
        subgraph 110 ["(110) FuncDefn: #quot;__main__.foo1#quot;"]
            direction LR
            111["(111) Input"]
            112["(112) Output"]
            subgraph 113 ["(113) CFG"]
                direction LR
                subgraph 114 ["(114) DataflowBlock"]
                    direction LR
                    115["(115) Input"]
                    116["(116) Output"]
                    117["(117) LoadConstant"]
                    118["(118) const:custom:u64(1)"]
                    119["(119) LoadConstant"]
                    120["(120) const:custom:u64(2)"]
                    121["(121) Call"]
                    122["(122) prelude.MakeTuple"]
                    123["(123) prelude.UnpackTuple"]
                    124["(124) tket.rotation.from_halfturns_unchecked"]
                    125["(125) tket.quantum.Rx"]
                    126["(126) prelude.MakeTuple"]
                    127["(127) Tag"]
                    115--"0:0<br>qubit"-->125
                    115-."1:3".->121
                    117--"0:0<br>int(6)"-->121
                    118--"0:0<br>int(6)"-->117
                    119--"0:1<br>int(6)"-->121
                    120--"0:0<br>int(6)"-->119
                    121--"0:0<br>float64"-->122
                    121-."1:2".->116
                    122--"0:0<br>[float64]"-->123
                    123--"0:0<br>float64"-->124
                    124--"0:1<br>rotation"-->125
                    125--"0:1<br>qubit"-->116
                    127--"0:0<br>Unit"-->116
                end
                128["(128) ExitBlock"]
                114-."0:0".->128
            end
            111--"0:0<br>qubit"-->113
            111-."1:1".->113
            113--"0:0<br>qubit"-->112
            113-."1:1".->112
        end
        subgraph 129 ["(129) FuncDefn: #quot;guppylang.std.num.int.__truediv__#quot;"]
            direction LR
            130["(130) Input"]
            131["(131) Output"]
            subgraph 132 ["(132) CFG"]
                direction LR
                subgraph 133 ["(133) DataflowBlock"]
                    direction LR
                    134["(134) Input"]
                    135["(135) Output"]
                    136["(136) arithmetic.conversions.convert_s"]
                    137["(137) arithmetic.conversions.convert_s"]
                    138["(138) arithmetic.float.fdiv"]
                    139["(139) Tag"]
                    134--"0:0<br>int(6)"-->136
                    134--"1:0<br>int(6)"-->137
                    136--"0:0<br>float64"-->138
                    137--"0:1<br>float64"-->138
                    138--"0:1<br>float64"-->135
                    139--"0:0<br>Unit"-->135
                end
                140["(140) ExitBlock"]
                133-."0:0".->140
            end
            130--"0:0<br>int(6)"-->132
            130--"1:1<br>int(6)"-->132
            132--"0:0<br>float64"-->131
        end
        subgraph 10 ["(10) FuncDefn: #quot;__modified____main__.foo1#quot;"]
            direction LR
            142["(142) Input"]
            143["(143) Output"]
            subgraph 144 ["(144) CFG"]
                direction LR
                subgraph 145 ["(145) DataflowBlock"]
                    direction LR
                    147["(147) Input"]
                    148["(148) Output"]
                    149["(149) tket.quantum.Rx"]
                    150["(150) tket.rotation.to_halfturns"]
                    151["(151) arithmetic.float.fneg"]
                    152["(152) tket.rotation.from_halfturns_unchecked"]
                    153["(153) tket.rotation.from_halfturns_unchecked"]
                    154["(154) prelude.UnpackTuple"]
                    155["(155) prelude.MakeTuple"]
                    156["(156) Call"]
                    157["(157) LoadConstant"]
                    158["(158) const:custom:u64(1)"]
                    159["(159) LoadConstant"]
                    160["(160) const:custom:u64(2)"]
                    161["(161) prelude.MakeTuple"]
                    162["(162) Tag"]
                    147--"0:0<br>qubit"-->149
                    149--"0:1<br>qubit"-->148
                    150--"0:0<br>float64"-->151
                    151--"0:0<br>float64"-->152
                    152--"0:1<br>rotation"-->149
                    153--"0:0<br>rotation"-->150
                    154--"0:0<br>float64"-->153
                    155--"0:0<br>[float64]"-->154
                    156--"0:0<br>float64"-->155
                    157--"0:0<br>int(6)"-->156
                    158--"0:0<br>int(6)"-->157
                    159--"0:1<br>int(6)"-->156
                    160--"0:0<br>int(6)"-->159
                    162--"0:0<br>Unit"-->148
                end
                146["(146) ExitBlock"]
                145-."0:0".->146
            end
            142--"0:0<br>qubit"-->144
            144--"0:0<br>qubit"-->143
        end
        subgraph 163 ["(163) FuncDefn: #quot;__modified____main__.foo3#quot;"]
            direction LR
            164["(164) Input"]
            165["(165) Output"]
            166["(166) collections.array.unpack"]
            subgraph 167 ["(167) CFG"]
                direction LR
                subgraph 169 ["(169) DataflowBlock"]
                    direction LR
                    171["(171) Input"]
                    172["(172) Output"]
                    173["(173) tket.quantum.H"]
                    174["(174) tket.quantum.H"]
                    175["(175) tket.quantum.CRz"]
                    176["(176) tket.rotation.to_halfturns"]
                    177["(177) arithmetic.float.fneg"]
                    178["(178) tket.rotation.from_halfturns_unchecked"]
                    179["(179) tket.rotation.from_halfturns_unchecked"]
                    180["(180) prelude.UnpackTuple"]
                    181["(181) prelude.MakeTuple"]
                    182["(182) arithmetic.float.fdiv"]
                    183["(183) arithmetic.conversions.convert_s"]
                    184["(184) LoadConstant"]
                    185["(185) const:custom:u64(2)"]
                    186["(186) prelude.MakeTuple"]
                    187["(187) Tag"]
                    171--"0:0<br>qubit"-->174
                    171--"1:0<br>float64"-->182
                    171--"2:0<br>qubit"-->175
                    173--"0:1<br>qubit"-->172
                    174--"0:1<br>qubit"-->175
                    175--"0:2<br>qubit"-->172
                    175--"1:0<br>qubit"-->173
                    176--"0:0<br>float64"-->177
                    177--"0:0<br>float64"-->178
                    178--"0:2<br>rotation"-->175
                    179--"0:0<br>rotation"-->176
                    180--"0:0<br>float64"-->179
                    181--"0:0<br>[float64]"-->180
                    182--"0:0<br>float64"-->181
                    183--"0:1<br>float64"-->182
                    184--"0:0<br>int(6)"-->183
                    185--"0:0<br>int(6)"-->184
                    187--"0:0<br>Unit"-->172
                end
                170["(170) ExitBlock"]
                169-."0:0".->170
            end
            168["(168) collections.array.new_array"]
            164--"0:0<br>array(1, qubit)"-->166
            164--"1:0<br>qubit"-->167
            164--"2:1<br>float64"-->167
            166--"0:2<br>qubit"-->167
            167--"0:1<br>qubit"-->165
            167--"1:0<br>qubit"-->168
            168--"0:0<br>array(1, qubit)"-->165
        end
        subgraph 188 ["(188) FuncDefn: #quot;__modified____main__.foo2#quot;"]
            direction LR
            189["(189) Input"]
            190["(190) Output"]
            191["(191) collections.array.unpack"]
            subgraph 192 ["(192) CFG"]
                direction LR
                subgraph 194 ["(194) DataflowBlock"]
                    direction LR
                    196["(196) Input"]
                    197["(197) Output"]
                    198["(198) tket.quantum.H"]
                    199["(199) tket.quantum.H"]
                    200["(200) tket.quantum.CRz"]
                    201["(201) tket.rotation.to_halfturns"]
                    202["(202) arithmetic.float.fneg"]
                    203["(203) tket.rotation.from_halfturns_unchecked"]
                    204["(204) const:custom:a(π*-0.25)"]
                    205["(205) LoadConstant"]
                    206["(206) const:custom:a(π*-0.5)"]
                    207["(207) LoadConstant"]
                    208["(208) tket.quantum.CRz"]
                    209["(209) tket.rotation.to_halfturns"]
                    210["(210) const:custom:f64(0.5)"]
                    211["(211) LoadConstant"]
                    212["(212) arithmetic.float.fmul"]
                    213["(213) tket.rotation.from_halfturns_unchecked"]
                    214["(214) tket.global_phase.global_phase"]
                    215["(215) tket.quantum.Rz"]
                    217["(217) tket.rotation.from_halfturns_unchecked"]
                    218["(218) prelude.UnpackTuple"]
                    219["(219) prelude.MakeTuple"]
                    220["(220) Call"]
                    221["(221) prelude.MakeTuple"]
                    222["(222) LoadConstant"]
                    223["(223) const:custom:u64(1)"]
                    224["(224) LoadConstant"]
                    225["(225) const:custom:u64(6)"]
                    226["(226) prelude.MakeTuple"]
                    227["(227) Tag"]
                    196--"0:0<br>qubit"-->199
                    196--"1:0<br>qubit"-->200
                    198--"0:1<br>qubit"-->208
                    199--"0:1<br>qubit"-->200
                    200--"0:0<br>qubit"-->208
                    200--"1:0<br>qubit"-->198
                    201--"0:0<br>float64"-->202
                    202--"0:0<br>float64"-->203
                    203--"0:2<br>rotation"-->200
                    204--"0:0<br>rotation"-->205
                    205--"0:0<br>rotation"-->209
                    205--"0:1<br>rotation"-->215
                    206--"0:0<br>rotation"-->207
                    207--"0:2<br>rotation"-->208
                    208--"0:0<br>qubit"-->215
                    208--"1:1<br>qubit"-->197
                    209--"0:0<br>float64"-->212
                    210--"0:0<br>float64"-->211
                    211--"0:1<br>float64"-->212
                    212--"0:0<br>float64"-->213
                    213--"0:0<br>rotation"-->214
                    215--"0:2<br>qubit"-->197
                    217--"0:0<br>rotation"-->201
                    218--"0:0<br>float64"-->217
                    219--"0:0<br>[float64]"-->218
                    220--"0:0<br>float64"-->219
                    222--"0:0<br>int(6)"-->220
                    223--"0:0<br>int(6)"-->222
                    224--"0:1<br>int(6)"-->220
                    225--"0:0<br>int(6)"-->224
                    227--"0:0<br>Unit"-->197
                end
                195["(195) ExitBlock"]
                194-."0:0".->195
            end
            193["(193) collections.array.new_array"]
            189--"0:0<br>array(1, qubit)"-->191
            189--"1:0<br>qubit"-->192
            191--"0:1<br>qubit"-->192
            192--"0:1<br>qubit"-->190
            192--"1:0<br>qubit"-->193
            193--"0:0<br>array(1, qubit)"-->190
        end
        subgraph 228 ["(228) FuncDefn: #quot;__modified____main__.main.__WithBlock__1#quot;"]
            direction LR
            229["(229) Input"]
            230["(230) Output"]
            231["(231) collections.array.unpack"]
            subgraph 232 ["(232) CFG"]
                direction LR
                subgraph 234 ["(234) DataflowBlock"]
                    direction LR
                    236["(236) Input"]
                    237["(237) Output"]
                    238["(238) Call"]
                    239["(239) collections.array.new_array"]
                    240["(240) collections.array.unpack"]
                    241["(241) Call"]
                    242["(242) collections.array.new_array"]
                    243["(243) collections.array.unpack"]
                    244["(244) Call"]
                    245["(245) prelude.MakeTuple"]
                    246["(246) prelude.MakeTuple"]
                    247["(247) Tag"]
                    236--"0:1<br>qubit"-->238
                    236--"1:0<br>qubit"-->239
                    238--"0:0<br>array(1, qubit)"-->240
                    238--"1:1<br>qubit"-->241
                    239--"0:0<br>array(1, qubit)"-->238
                    240--"0:0<br>qubit"-->242
                    241--"0:0<br>array(1, qubit)"-->243
                    241--"1:1<br>qubit"-->237
                    242--"0:0<br>array(1, qubit)"-->241
                    243--"0:2<br>qubit"-->237
                    244--"0:2<br>float64"-->238
                    247--"0:0<br>Unit"-->237
                end
                235["(235) ExitBlock"]
                234-."0:0".->235
            end
            233["(233) collections.array.new_array"]
            229--"0:0<br>array(1, qubit)"-->231
            229--"1:0<br>qubit"-->232
            231--"0:1<br>qubit"-->232
            232--"0:1<br>qubit"-->230
            232--"1:0<br>qubit"-->233
            233--"0:0<br>array(1, qubit)"-->230
        end
        subgraph 249 ["(249) FuncDefn: #quot;__modified____main__.main.__WithBlock__0#quot;"]
            direction LR
            250["(250) Input"]
            251["(251) Output"]
            subgraph 252 ["(252) CFG"]
                direction LR
                subgraph 253 ["(253) DataflowBlock"]
                    direction LR
                    255["(255) Input"]
                    256["(256) Output"]
                    257["(257) Call"]
                    258["(258) collections.borrow_arr.new_array"]
                    259["(259) collections.borrow_arr.to_array"]
                    260["(260) LoadFunction"]
                    261["(261) CallIndirect"]
                    262["(262) collections.borrow_arr.from_array"]
                    263["(263) collections.borrow_arr.unpack"]
                    264["(264) prelude.MakeTuple"]
                    265["(265) Tag"]
                    255--"0:0<br>qubit"-->257
                    255--"1:2<br>qubit"-->261
                    257--"0:0<br>qubit"-->258
                    258--"0:0<br>borrow_array(1, qubit)"-->259
                    259--"0:1<br>array(1, qubit)"-->261
                    260--"0:0<br>[array(1, qubit), qubit] -> [array(1, qubit), qubit]"-->261
                    261--"0:0<br>array(1, qubit)"-->262
                    261--"1:2<br>qubit"-->256
                    262--"0:0<br>borrow_array(1, qubit)"-->263
                    263--"0:1<br>qubit"-->256
                    265--"0:0<br>Unit"-->256
                end
                254["(254) ExitBlock"]
                253-."0:0".->254
            end
            250--"0:0<br>qubit"-->252
            250--"1:1<br>qubit"-->252
            252--"0:0<br>qubit"-->251
            252--"1:1<br>qubit"-->251
        end
        43--"0:0<br>[qubit] -> [qubit]"-->32
        57--"0:0<br>[] -> [float64]"-->50
        57--"0:0<br>[] -> [float64]"-->244
        71--"0:1<br>[qubit] -> [qubit]"-->51
        92--"0:2<br>[qubit, float64] -> [qubit]"-->53
        110--"0:1<br>[qubit] -> [qubit]"-->39
        129--"0:2<br>[int(6), int(6)] -> [float64]"-->68
        129--"0:2<br>[int(6), int(6)] -> [float64]"-->84
        129--"0:2<br>[int(6), int(6)] -> [float64]"-->121
        129--"0:2<br>[int(6), int(6)] -> [float64]"-->156
        129--"0:2<br>[int(6), int(6)] -> [float64]"-->220
        10--"0:1<br>[qubit] -> [qubit]"-->257
        163--"0:3<br>[array(1, qubit), qubit, float64] -> [array(1, qubit), qubit]"-->238
        188--"0:2<br>[array(1, qubit), qubit] -> [array(1, qubit), qubit]"-->241
        228--"0:0<br>[array(1, qubit), qubit] -> [array(1, qubit), qubit]"-->260
        249--"0:0<br>[qubit, qubit] -> [qubit, qubit]"-->266
    end
