---
config:
    layout: elk
---
graph LR
    subgraph 0 ["(0) [**Module**]"]
        direction LR
        style 0 stroke:#832561,stroke-width:3px
        subgraph 1 ["(1) FuncDefn: #quot;foo#quot;"]
            direction LR
            2["(2) Input"]
            3["(3) Output"]
            4["(4) tket.quantum.Vdg"]
            2--"0:0<br>qubit"-->4
            2--"1:1<br>qubit"-->3
            2--"2:2<br>qubit"-->3
            4--"0:0<br>qubit"-->3
        end
        subgraph 5 ["(5) FuncDefn: #quot;main#quot;"]
            direction LR
            6["(6) Input"]
            7["(7) Output"]
            8["(8) LoadFunction"]
            9["(9) tket.modifier.ControlModifier"]
            10["(10) tket.quantum.QAlloc"]
            11["(11) tket.quantum.QAlloc"]
            12["(12) tket.quantum.QAlloc"]
            13["(13) tket.quantum.QAlloc"]
            14["(14) tket.quantum.QAlloc"]
            15["(15) tket.quantum.QAlloc"]
            16["(16) tket.quantum.QAlloc"]
            17["(17) tket.quantum.QAlloc"]
            18["(18) tket.quantum.QAlloc"]
            19["(19) tket.quantum.QAlloc"]
            20["(20) collections.array.new_array"]
            21["(21) CallIndirect"]
            8--"0:0<br>[qubit, qubit, qubit] -> [qubit, qubit, qubit]"-->9
            9--"0:0<br>[array(7, qubit), qubit, qubit, qubit] -> [array(7, qubit), qubit, qubit, qubit]"-->21
            10--"0:0<br>qubit"-->20
            11--"0:1<br>qubit"-->20
            12--"0:2<br>qubit"-->20
            13--"0:3<br>qubit"-->20
            14--"0:4<br>qubit"-->20
            15--"0:5<br>qubit"-->20
            16--"0:6<br>qubit"-->20
            17--"0:2<br>qubit"-->21
            18--"0:3<br>qubit"-->21
            19--"0:4<br>qubit"-->21
            20--"0:1<br>array(7, qubit)"-->21
            21--"0:0<br>array(7, qubit)"-->7
            21--"1:1<br>qubit"-->7
            21--"2:2<br>qubit"-->7
            21--"3:3<br>qubit"-->7
        end
        1--"0:0<br>[qubit, qubit, qubit] -> [qubit, qubit, qubit]"-->8
    end
