---
config:
    layout: elk
---
graph LR
    subgraph 0 ["(0) Module"]
        direction LR
        subgraph 1 ["(1) [**FuncDefn: #quot;__main__.bar#quot;**]"]
            direction LR
            style 1 stroke:#832561,stroke-width:3px
            2["(2) Input"]
            3["(3) Output"]
            subgraph 4 ["(4) DFG"]
                direction LR
                5["(5) Input"]
                6["(6) Output"]
                58["(58) LoadFunction"]
                9["(9) collections.borrow_arr.new_array"]
                10["(10) collections.borrow_arr.to_array"]
                11["(11) CallIndirect"]
                12["(12) collections.borrow_arr.from_array"]
                13["(13) collections.borrow_arr.unpack"]
                14["(14) Tag"]
                15["(15) prelude.UnpackTuple"]
                5--"0:0<br>qubit"-->9
                5-."1:2".->11
                58--"0:0<br>[array(1, qubit)] -> [array(1, qubit)]"-->11
                9--"0:0<br>borrow_array(1, qubit)"-->10
                10--"0:1<br>array(1, qubit)"-->11
                11--"0:0<br>array(1, qubit)"-->12
                11-."1:1".->6
                12--"0:0<br>borrow_array(1, qubit)"-->13
                13--"0:0<br>qubit"-->6
                14--"0:0<br>Unit"-->15
            end
            2--"0:0<br>qubit"-->4
            2-."1:1".->4
            4--"0:0<br>qubit"-->3
            4-."1:1".->3
        end
        subgraph 16 ["(16) FuncDefn: #quot;__main__.bar.__WithBlock__0#quot;"]
            direction LR
            17["(17) Input"]
            18["(18) Output"]
            subgraph 19 ["(19) DFG"]
                direction LR
                20["(20) Input"]
                21["(21) Output"]
                22["(22) LoadFunction"]
                23["(23) tket.modifier.DaggerModifier"]
                24["(24) CallIndirect"]
                25["(25) Tag"]
                26["(26) prelude.UnpackTuple"]
                20-."0:1".->24
                22--"0:0<br>[] -> []"-->23
                23--"0:0<br>[] -> []"-->24
                24-."0:0".->21
                25--"0:0<br>Unit"-->26
            end
            17-."0:0".->19
            19-."0:0".->18
        end
        subgraph 27 ["(27) FuncDefn: #quot;__main__.bar.__WithBlock__1#quot;"]
            direction LR
            28["(28) Input"]
            29["(29) Output"]
            subgraph 30 ["(30) DFG"]
                direction LR
                31["(31) Input"]
                32["(32) Output"]
                33["(33) Tag"]
                34["(34) prelude.UnpackTuple"]
                33--"0:0<br>Unit"-->34
            end
        end
        subgraph 7 ["(7) FuncDefn: #quot;__modified____main__.bar.__WithBlock__1#quot;"]
            direction LR
            35["(35) Input"]
            36["(36) Output"]
            37["(37) collections.array.unpack"]
            subgraph 38 ["(38) DFG"]
                direction LR
                40["(40) Input"]
                41["(41) Output"]
                42["(42) Tag"]
                43["(43) prelude.UnpackTuple"]
                42--"0:0<br>Unit"-->43
            end
            39["(39) collections.array.new_array"]
            35--"0:0<br>array(1, qubit)"-->37
            37--"0:0<br>qubit"-->39
            39--"0:0<br>array(1, qubit)"-->36
        end
        subgraph 44 ["(44) FuncDefn: #quot;__modified____main__.bar.__WithBlock__0#quot;"]
            direction LR
            45["(45) Input"]
            46["(46) Output"]
            47["(47) collections.array.unpack"]
            subgraph 48 ["(48) DFG"]
                direction LR
                50["(50) Input"]
                51["(51) Output"]
                52["(52) Tag"]
                53["(53) prelude.UnpackTuple"]
                54["(54) LoadFunction"]
                55["(55) CallIndirect"]
                56["(56) collections.array.new_array"]
                57["(57) collections.array.unpack"]
                50--"0:0<br>qubit"-->56
                52--"0:0<br>Unit"-->53
                54--"0:0<br>[array(1, qubit)] -> [array(1, qubit)]"-->55
                55--"0:0<br>array(1, qubit)"-->57
                56--"0:1<br>array(1, qubit)"-->55
                57--"0:0<br>qubit"-->51
            end
            49["(49) collections.array.new_array"]
            45--"0:0<br>array(1, qubit)"-->47
            47--"0:0<br>qubit"-->48
            48--"0:0<br>qubit"-->49
            49--"0:0<br>array(1, qubit)"-->46
        end
        27--"0:0<br>[] -> []"-->22
        7--"0:0<br>[array(1, qubit)] -> [array(1, qubit)]"-->54
        44--"0:0<br>[array(1, qubit)] -> [array(1, qubit)]"-->58
    end
