[package]
name = "tk-pg-greedy-synth"
version = "0.1.0"
edition = { workspace = true }
rust-version = { workspace = true }

[features]
default = []
simd = ["tk-pg-qm-tableau/simd", "tk-pg-bitpacked/simd"]

[dependencies]
crossbeam-skiplist = "0.1.3"
indexmap = { workspace = true }
indicatif = { workspace = true }
tk-pg-bitpacked = { path = "../../pg-kernels/tk-pg-bitpacked" }
tk-pg-canonical-form = { path = "../tk-pg-canonical-form" }
tk-pg-core = { path = "../../tk-pg-core" }
tk-pg-optimise = { path = "../tk-pg-optimise" }
tk-pg-qm-tableau = { path = "../../tk-pg-qm-tableau" }
rand = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
tk-pg-ir-kernels = { path = "../../pg-kernels/tk-pg-ir-kernels" }
tk-pg-tk = { path = "../../pg-converters/tk-pg-tk" }
rstest = { workspace = true }

[lints]
workspace = true
