// Prepared test-only ABI harness. This models only the calls generated by the
// proposed adapter, not production cancellation, reclamation or native APIs.
use std::{
    alloc::{Layout, alloc, dealloc},
    cell::RefCell,
    collections::BTreeSet,
    ptr::NonNull,
    sync::{
        Mutex,
        atomic::{AtomicBool, AtomicU64, Ordering},
    },
};

#[derive(Clone, Debug, PartialEq, Eq)]
pub(super) enum Event {
    Create { size: u64, alignment: u64 },
    Adjust { delta: i64, final_owner: bool },
    Lock,
    Project,
    Unlock,
    Destroy,
}

thread_local! {
    pub(super) static EVENTS: RefCell<Vec<Event>> = const { RefCell::new(Vec::new()) };
    static HELD: RefCell<BTreeSet<usize>> = const { RefCell::new(BTreeSet::new()) };
}
static LIVE: Mutex<BTreeSet<usize>> = Mutex::new(BTreeSet::new());

fn assert_live(handle: *mut Cell) {
    assert!(
        LIVE.lock().unwrap().contains(&(handle as usize)),
        "access after final release"
    );
}

fn event(event: Event) {
    EVENTS.with_borrow_mut(|events| events.push(event));
}

// Metadata is entirely runtime-owned and cannot be reached through projection.
// The separately allocated data contains exactly the LLVM value bytes.
pub(super) struct Cell {
    owners: AtomicU64,
    locked: AtomicBool,
    data: NonNull<u8>,
    allocation: Layout,
    size: usize,
}

pub(super) unsafe extern "C" fn create(size: u64, alignment: u64, source: *const u8) -> *mut Cell {
    let allocation = Layout::from_size_align((size as usize).max(1), alignment as usize).unwrap();
    let data = NonNull::new(unsafe { alloc(allocation) }).unwrap();
    if size != 0 {
        // Copying bytes preserves potentially uninitialized LLVM padding.
        unsafe { std::ptr::copy_nonoverlapping(source, data.as_ptr(), size as usize) };
    }
    event(Event::Create { size, alignment });
    let handle = Box::into_raw(Box::new(Cell {
        owners: AtomicU64::new(1),
        locked: AtomicBool::new(false),
        data,
        allocation,
        size: size as usize,
    }));
    assert!(LIVE.lock().unwrap().insert(handle as usize));
    handle
}

pub(super) unsafe extern "C" fn lock(handle: *mut Cell) {
    assert_live(handle);
    HELD.with_borrow(|held| assert!(!held.contains(&(handle as usize))));
    let cell = unsafe { &*handle };
    while cell
        .locked
        .compare_exchange_weak(false, true, Ordering::Acquire, Ordering::Relaxed)
        .is_err()
    {
        std::hint::spin_loop();
    }
    HELD.with_borrow_mut(|held| assert!(held.insert(handle as usize)));
    event(Event::Lock);
}

pub(super) unsafe extern "C" fn unlock(handle: *mut Cell) {
    assert_live(handle);
    HELD.with_borrow_mut(|held| assert!(held.remove(&(handle as usize))));
    let cell = unsafe { &*handle };
    cell.locked.store(false, Ordering::Release);
    event(Event::Unlock);
}

pub(super) unsafe extern "C" fn data(handle: *mut Cell) -> *mut u8 {
    assert_live(handle);
    HELD.with_borrow(|held| assert!(held.contains(&(handle as usize))));
    event(Event::Project);
    unsafe { (*handle).data.as_ptr() }
}

pub(super) unsafe extern "C" fn adjust(
    handle: *mut Cell,
    delta: i64,
    destination: *mut u8,
) -> bool {
    assert_live(handle);
    // Generated Dup and Free must not use the common payload-lock path.
    HELD.with_borrow(|held| assert!(!held.contains(&(handle as usize))));
    assert!(matches!(delta, -1 | 1));
    let cell = unsafe { &*handle };
    let previous = cell
        .owners
        .fetch_update(Ordering::AcqRel, Ordering::Acquire, |owners| {
            assert!(owners > 0);
            owners.checked_add_signed(delta)
        })
        .unwrap();
    let final_owner = delta == -1 && previous == 1;
    event(Event::Adjust { delta, final_owner });
    if !final_owner {
        // In particular, do not write the destination for a nonfinal release.
        return false;
    }
    assert!(
        !destination.is_null(),
        "HUGR Free must recover its linear value"
    );
    while cell
        .locked
        .compare_exchange_weak(false, true, Ordering::Acquire, Ordering::Relaxed)
        .is_err()
    {
        std::hint::spin_loop();
    }
    if cell.size != 0 {
        unsafe { std::ptr::copy_nonoverlapping(cell.data.as_ptr(), destination, cell.size) };
    }
    // End the borrowed view before retiring the final owned handle/storage.
    let allocation = cell.allocation;
    let payload = cell.data;
    assert!(LIVE.lock().unwrap().remove(&(handle as usize)));
    unsafe {
        drop(Box::from_raw(handle));
        dealloc(payload.as_ptr(), allocation);
    }
    event(Event::Destroy);
    true
}
