[package]
name = "tket-migrate"
version = "0.1.0"
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
description = "Migrate HUGR extension operations and types between versions"

[lints]
workspace = true

[dependencies]
hugr.workspace = true
serde_json.workspace = true
thiserror = { workspace = true }
tket = { path = "../tket-rs" }
